### PR TITLE
Ignore patterns & customizable decorator string

### PR DESCRIPTION
**Pull request by jaredh159**
Hi there!  Thanks for the great package.  I really like how it's much less intrusive than the code lens package json plugin.

For my use case, I really only care about seeing updates for my own monorepo packages, so I took a stab and implemented the requested feature from https://github.com/pgsandstrom/package-json-upgrade/issues/17 that you seemed to like, although not exactly as the OP suggested.  I made it so you can have an array of _ignore patterns_, like so:

```json
{
  "package-json-upgrade.ignorePatterns": [
    "^(?!@friends-library).+$"
  ],
}
```

Works great and seems flexible enough to support most use-cases.

And then (in hindsight maybe I should have separated this out into a separate PR, sorry, let me know if you want me to do that), I wanted to customize the string output to be more subtle, what I was going for was this:

So I quick implemented a feature allowing customization of the default `Update available for: <semver>`, allowing this in the settings:

```json
{
  "package-json-upgrade.decorationString": "%s",
}
```

I used a C/printf style placeholder of `%s` to represent where to put the semver string, as you can see in the code.

I can write up a bit of documentation on these options in the readme, if you are up for merging.  Thanks again!

### CODE REVIEW

**Comment by pgsandstrom** [comment]
Hey! Thanks for a great PR! I haven't had the time to keep this extension up to date, so it feels great to see good work on it :)

First of all, you have to add some stuff to package.json for each config option you add. Like this:

```
        "package-json-upgrade.decorationString": {
          "type": "string",
          "default": "\t\tUpdate available: %s",
          "description": "Customize update string. %s will be replaced by version, so 'Update: %s' will result in 'Update: 1.0.1'."
        },
        "package-json-upgrade.ignorePatterns": {
          "type": "array",
          "default": [],
          "description": "Regex pattern of packages to not show decoration string for. To ignore all material-ui packages the JSON should be [\"^(?=@material-ui).+$\"]"
        }
```

You can see the other configurations in package.json. Actually Im not sure how you got it working without this. Am I missing something? :P If you can think of a better description than what I just threw together you are very welcome to change it.

Then we should also add some code so we always fall back to the default string if the decorationString option is just the empty string. Currently that will not happen since we use nullish coalescing in the config file.

Could you also do some quick bug testing with what happens if you input weird config values? I tried adding some invalid regex and it resultet in a crash. Perhaps we could catch the error and show a notification or something? See https://code.visualstudio.com/api/references/extension-guidelines#notifications

**Comment by jaredh159** [comment]
Ok,  I think I addressed all your concerns now.  I'm not sure how it was working without the package.json changes, but it was! :)

I tested some garbage regexes and got the extension to hand saying "Loading updates...", but I never got a crash.  But I did verify that with the new code, bad regexes that are throwing errors are now caught, and a simple error message is shown:



For the fallback decoration string (in the case where someone enters an empty string), I was fighting your lint rules a little bit, because by changing `??` to `||` we get exactly (I think) what you were wanting -- we fall back on _any falsy_ value (including the empty string). But your lint rules didn't like me, even though I was very intentionally using the logical or operator because of how it handles the empty string.  If you don't like the lint-disable line, we could modify the lint rules, or I could rewrite the assignment in away that the linter is happy with.

**Comment by pgsandstrom** [comment]
It looks great! I have no problem with the eslint-disable line :)

**Comment by pgsandstrom** [comment]
The new release should be out in a moment. Thank you again for the great PR! Let me know if you run into any issues.

**Comment by jaredh159** [comment]
@pgsandstrom awesome, thanks!  I forgot to mark that this closes #17 -- you might want to close that one out.  Thanks again for the great plugin!

**Pull request merged**
